version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    image: todo-app:prod
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $PROD_DB_USER
      POSTGRES_DB: $PROD_DB
      POSTGRES_PASSWORD: $PROD_DB_PASSWORD

volumes:
  pg-prod-data: